/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ronaldo_3d_card.glb 
Author: Peter Charles (https://sketchfab.com/dk3510329)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cristiano-ronaldo-3d-model-94b54aedd12b4cfb90cd972277997025
Title: Cristiano Ronaldo 3d model
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function RonaldoCard(props) {
  const { scene } = useGLTF('/model/ronaldo_3d_card.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <primitive object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.AvatarBody} skeleton={nodes.Object_6.skeleton} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.AvatarEyelashes} skeleton={nodes.Object_7.skeleton} />
      <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.AvatarHead} skeleton={nodes.Object_8.skeleton} />
      <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.AvatarLeftCornea} skeleton={nodes.Object_9.skeleton} />
      <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.AvatarLeftEyeball} skeleton={nodes.Object_10.skeleton} />
      <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.AvatarRightCornea} skeleton={nodes.Object_11.skeleton} />
      <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.AvatarRightEyeball} skeleton={nodes.Object_12.skeleton} />
      <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.AvatarTeethLower} skeleton={nodes.Object_13.skeleton} />
      <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.AvatarTeethUpper} skeleton={nodes.Object_14.skeleton} />
      <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.outfit_bottom} skeleton={nodes.Object_15.skeleton} />
      <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.outfit_shoes} skeleton={nodes.Object_16.skeleton} />
      <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.outfit_top} skeleton={nodes.Object_17.skeleton} />
    </group>
  )
}

useGLTF.preload('/model/ronaldo_3d_card.glb')
