import React, { createContext, useEffect, useState } from "react";

export const recipeContext = createContext(null);

const RecipeContext = ({ children }) => {
  const [data, setdata] = useState([
    // {
    //   id: 1,
    //   title: "Classic Margherita Pizza",
    //   ingr: [
    //     "Pizza dough",
    //     "Tomato sauce",
    //     "Fresh mozzarella cheese",
    //     "Fresh basil leaves",
    //     "Olive oil",
    //     "Salt and pepper to taste",
    //   ],
    //   instructions: [
    //     "Preheat the oven to 475°F (245°C).",
    //     "Roll out the pizza dough and spread tomato sauce evenly.",
    //     "Top with slices of fresh mozzarella and fresh basil leaves.",
    //     "Drizzle with olive oil and season with salt and pepper.",
    //     "Bake in the preheated oven for 12-15 minutes or until the crust is golden brown.",
    //     "Slice and serve hot.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/1.webp",
    //   chef: "abhi",
    //   category: "dinner",
    //   desc: "Drizzle with olive oil and season with salt and pepper.",
    // },
    // {
    //   id: 2,
    //   title: "Vegetarian Stir-Fry",
    //   ingr: [
    //     "Tofu, cubed",
    //     "Broccoli florets",
    //     "Carrots, sliced",
    //     "Bell peppers, sliced",
    //     "Soy sauce",
    //     "Ginger, minced",
    //     "Garlic, minced",
    //     "Sesame oil",
    //     "Cooked rice for serving",
    //   ],
    //   instructions: [
    //     "In a wok, heat sesame oil over medium-high heat.",
    //     "Add minced ginger and garlic, sauté until fragrant.",
    //     "Add cubed tofu and stir-fry until golden brown.",
    //     "Add broccoli, carrots, and bell peppers. Cook until vegetables are tender-crisp.",
    //     "Pour soy sauce over the stir-fry and toss to combine.",
    //     "Serve over cooked rice.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/2.webp",
    //   chef: "SalluBhai",
    //   desc: "Add broccoli, carrots, and bell peppers. Cook until vegetables are tender-crisp.",
    // },
    // {
    //   id: 3,
    //   title: "Chocolate Chip Cookies",
    //   ingr: [
    //     "All-purpose flour",
    //     "Butter, softened",
    //     "Brown sugar",
    //     "White sugar",
    //     "Eggs",
    //     "Vanilla extract",
    //     "Baking soda",
    //     "Salt",
    //     "Chocolate chips",
    //   ],
    //   instructions: [
    //     "Preheat the oven to 350°F (175°C).",
    //     "In a bowl, cream together softened butter, brown sugar, and white sugar.",
    //     "Beat in eggs one at a time, then stir in vanilla extract.",
    //     "Combine flour, baking soda, and salt. Gradually add to the wet ingredients.",
    //     "Fold in chocolate chips.",
    //     "Drop rounded tablespoons of dough onto ungreased baking sheets.",
    //     "Bake for 10-12 minutes or until edges are golden brown.",
    //     "Allow cookies to cool on the baking sheet for a few minutes before transferring to a wire rack.",
    //   ],
    //   chef: "Rohit",
    //   image: "https://cdn.dummyjson.com/recipe-images/3.webp",
    //   desc: "Drop rounded tablespoons of dough onto ungreased baking sheets.",
    // },
    // {
    //   id: 4,
    //   title: "Paneer Butter Masala",
    //   ingr: [
    //     "Paneer cubes",
    //     "Tomatoes",
    //     "Onion",
    //     "Butter",
    //     "Fresh cream",
    //     "Ginger garlic paste",
    //     "Spices",
    //   ],
    //   instructions: [
    //     "Saute onions and tomatoes.",
    //     "Blend into a smooth gravy.",
    //     "Cook with spices and butter.",
    //     "Add paneer cubes and cream.",
    //     "Simmer for 10 minutes and serve.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/4.webp",
    //   chef: "Aman",
    //   category: "dinner",
    //   desc: "Creamy and rich paneer curry perfect with naan.",
    // },
    // {
    //   id: 5,
    //   title: "Chicken Biryani",
    //   ingr: [
    //     "Chicken",
    //     "Basmati rice",
    //     "Onions",
    //     "Yogurt",
    //     "Biryani masala",
    //     "Mint leaves",
    //   ],
    //   instructions: [
    //     "Marinate chicken with yogurt and spices.",
    //     "Cook rice until 70% done.",
    //     "Layer rice and chicken.",
    //     "Cook on dum for 25 minutes.",
    //     "Serve hot.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/5.webp",
    //   chef: "Faizan",
    //   category: "dinner",
    //   desc: "Aromatic biryani loaded with spices and flavors.",
    // },
    // {
    //   id: 6,
    //   title: "Masala Dosa",
    //   ingr: [
    //     "Dosa batter",
    //     "Potatoes",
    //     "Onions",
    //     "Mustard seeds",
    //     "Curry leaves",
    //   ],
    //   instructions: [
    //     "Prepare potato masala.",
    //     "Spread dosa batter on hot tawa.",
    //     "Cook until crispy.",
    //     "Add potato filling.",
    //     "Fold and serve.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/6.webp",
    //   chef: "Priya",
    //   category: "breakfast",
    //   desc: "South Indian crispy dosa stuffed with potato filling.",
    // },
    // {
    //   id: 7,
    //   title: "Veg Burger",
    //   ingr: [
    //     "Burger buns",
    //     "Veg patty",
    //     "Lettuce",
    //     "Tomato",
    //     "Cheese slice",
    //     "Mayonnaise",
    //   ],
    //   instructions: [
    //     "Toast burger buns.",
    //     "Cook veg patty.",
    //     "Assemble with veggies and cheese.",
    //     "Add mayonnaise.",
    //     "Serve immediately.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/7.webp",
    //   chef: "Neha",
    //   category: "lunch",
    //   desc: "Juicy vegetarian burger with fresh vegetables.",
    // },
    // {
    //   id: 8,
    //   title: "Mango Smoothie",
    //   ingr: ["Mango", "Milk", "Honey", "Ice cubes"],
    //   instructions: [
    //     "Add all ingredients to blender.",
    //     "Blend until smooth.",
    //     "Pour into a glass.",
    //     "Serve chilled.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/8.webp",
    //   chef: "Karan",
    //   category: "drink",
    //   desc: "Refreshing mango smoothie perfect for summer.",
    // },
    // {
    //   id: 9,
    //   title: "Pasta Alfredo",
    //   ingr: ["Pasta", "Butter", "Garlic", "Fresh cream", "Parmesan cheese"],
    //   instructions: [
    //     "Cook pasta until al dente.",
    //     "Prepare Alfredo sauce.",
    //     "Mix pasta with sauce.",
    //     "Top with cheese.",
    //     "Serve hot.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/9.webp",
    //   chef: "Rahul",
    //   category: "dinner",
    //   desc: "Creamy white sauce pasta loaded with cheese.",
    // },
    // {
    //   id: 10,
    //   title: "French Toast",
    //   ingr: ["Bread slices", "Eggs", "Milk", "Sugar", "Butter"],
    //   instructions: [
    //     "Whisk eggs, milk and sugar.",
    //     "Dip bread slices.",
    //     "Cook on buttered pan.",
    //     "Flip until golden.",
    //     "Serve warm.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/10.webp",
    //   chef: "Anjali",
    //   category: "breakfast",
    //   desc: "Classic French toast with a crispy golden texture.",
    // },
    // {
    //   id: 11,
    //   title: "Caesar Salad",
    //   ingr: ["Lettuce", "Croutons", "Parmesan cheese", "Caesar dressing"],
    //   instructions: [
    //     "Wash and chop lettuce.",
    //     "Add croutons and cheese.",
    //     "Drizzle dressing.",
    //     "Toss well and serve.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/11.webp",
    //   chef: "Riya",
    //   category: "lunch",
    //   desc: "Fresh and healthy Caesar salad.",
    // },
    // {
    //   id: 12,
    //   title: "Chocolate Brownie",
    //   ingr: ["Dark chocolate", "Butter", "Sugar", "Eggs", "Flour"],
    //   instructions: [
    //     "Melt chocolate and butter.",
    //     "Mix sugar and eggs.",
    //     "Combine all ingredients.",
    //     "Bake for 30 minutes.",
    //     "Cool before slicing.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/12.webp",
    //   chef: "Vikram",
    //   category: "dessert",
    //   desc: "Rich and fudgy chocolate brownie.",
    // },
    // {
    //   id: 13,
    //   title: "Grilled Sandwich",
    //   ingr: ["Bread", "Cheese", "Tomato", "Onion", "Butter"],
    //   instructions: [
    //     "Layer vegetables and cheese.",
    //     "Butter bread slices.",
    //     "Grill until golden brown.",
    //     "Cut and serve.",
    //   ],
    //   image: "https://cdn.dummyjson.com/recipe-images/13.webp",
    //   chef: "Meera",
    //   category: "snack",
    //   desc: "Crispy grilled sandwich with melted cheese.",
    // },
  ]);



  
  useEffect(() => {
    // localStorage.setItem("recipe", JSON.stringify(data))
    setdata(JSON.parse(localStorage.getItem("recipe")) || [])
  }, []);
  return <recipeContext.Provider value={[data, setdata]}>{children}</recipeContext.Provider>;
};

export default RecipeContext;
